# Generated by Django 5.1.1 on 2024-10-04 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('products_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('available_stock', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('category', models.CharField(choices=[('Clo', 'Clothes'), ('Toi', 'Toilettries'), ('Kit', 'Kithen'), ('Fur', 'Furniture')], max_length=3)),
                ('image', models.URLField()),
            ],
        ),
    ]
