# Generated by Django 5.1.1 on 2024-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clo', 'Clothes'), ('Toi', 'Toilettries'), ('Kit', 'Kithen'), ('Fur', 'Furniture'), ('Eat', 'Eatables')], max_length=3),
        ),
    ]
